### ISSUE TITLE
cAppPool - password is blank

### ISSUE THREAD

**Issue by lukee8** [PowerShellOrg/cWebAdministration#18]
I'm creating application pool this way:

$credAppPoolUser 		= "appPool1"
$credAppPoolPassword 	= "password.1" | ConvertTo-SecureString -asPlainText -Force
$credAppPool			= New-Object System.Management.Automation.PSCredential($credAppPoolUser,$credAppPoolPassword)

cAppPool Website1_AppPoolName
{ 
	Name					= "appPool1"
	Ensure					= "Present" 
	autoStart				= "true"  
	managedRuntimeVersion	= "v4.0"
	managedPipelineMode		= "Integrated"
	startMode				= "AlwaysRunning"
	identityType			= "SpecificUser"
	userName				= $credAppPoolUser
	Password				= $credAppPool
	loadUserProfile			= "true"
	idleTimeout				= "00:00:00"
	shutdownTimeLimit		= "00:05:00"
	logEventOnRecycle		= "ConfigChange, IsapiUnhealthy, OnDemand, PrivateMemory, Time, Requests, Schedule, Memory"
	restartTimeLimit		= "00:00:00"
	DependsOn				= @("[WindowsFeature]IIS") 
} 
	

In MOF file I've got:

instance of MSFT_Credential as $MSFT_Credential3ref
{
Password = "password.1";
 UserName = "domainName\\testUser";

};

instance of PSHOrg_cAppPool as $PSHOrg_cAppPool3ref
{
autoStart = "true";
 idleTimeout = "00:00:00";
 Name = "appPool1";
 ResourceID = "[cAppPool]Website1_AppPoolName";
 userName = "domainName\\testUser";
 Password = $MSFT_Credential3ref;
 identityType = "SpecificUser";
 loadUserProfile = "true";
 logEventOnRecycle = "ConfigChange, IsapiUnhealthy, OnDemand, PrivateMemory, Time, Requests, Schedule, Memory";
 Ensure = "Present";
 restartTimeLimit = "00:00:00";
 SourceInfo = "D:\\PlatformProvisioning.ps1::182::3::cAppPool";
 managedRuntimeVersion = "v4.0";
 shutdownTimeLimit = "00:05:00";
 ModuleVersion = "2.0.0";
 ModuleName = "cWebAdministration";
 startMode = "AlwaysRunning";
 managedPipelineMode = "Integrated";

DependsOn = {

    "[WindowsFeature]IIS"};

};

For me it looks fine. But after all application pool is stopped (wrong credential), 
Checking password with "Get-ItemProperty IIS:\AppPools\AppPool1 -name processModel" shows that password is blank. 

If I'm running code from psm1 file to set password (with variables set properly):
$clearTextPassword = $Password.GetNetworkCredential().Password
                if($clearTextPassword -eq $PoolConfig.add.processModel.password){
                    $UpdateNotRequired = $false
                    & $env:SystemRoot\system32\inetsrv\appcmd.exe set apppool $Name /processModel.password:$clearTextPassword
then it works. Looks like that somewhere earlier in code something going wrong way...

**Comment by lukee8** [comment]
Nobody tried to set user account for application pool?

**Comment by youannes** [comment]
getting the same problem when setting password. Any word on a fix?

**Comment by lukee8** [comment]
Last week I updated cWebAdministration modules in my environment to version 2.0.1 and now password is correct.

**Comment by lukee8** [comment]
The problem is that I have ampersand (&) in app pool password.
The solution could be to replace PSHOrg_cAppPool.psm1 line 786

[xml]$PoolConfig = & $env:SystemRoot\system32\inetsrv\appcmd.exe list apppool $Name /config:*

with

[xml]$PoolConfig = (& $env:SystemRoot\system32\inetsrv\appcmd.exe list apppool paAash /config:*).Replace("&", "&amp;")

Could anybody make a commit with this change?
