### ISSUE TITLE
Adding cWebAdministration to the Powershell Gallery

### ISSUE THREAD

**Issue by ipartington** [PowerShellOrg/cWebAdministration#27]
Hi There just wondering if there are any plans to add this to the PowerShell Gallery?

https://www.powershellgallery.com/

Cheers

**Comment by dlwyatt** [comment]
Probably not. Better would be to just make sure everything gets merged into xWebAdministration, if it hasn't already.

On Jun 5, 2016, at 12:14 PM, Iain Partington <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi There just wondering if there are any plans to add this to the PowerShell Gallery?

https://www.powershellgallery.com/

Cheers

-

**Comment by ipartington** [comment]
Thanks
